{% set laim = pillar.get('laim', {}) -%}

###################################
# File managed by salt state laim #
###################################

# Include some useful properties by default
hostname: "{{ grains.id }}"

{{ laim.get('config', {}) | yaml(False) }}
