{% set laim = pillar.get('laim', {}) -%}

###################################
# File managed by salt state laim #
###################################

# Include some useful properties by default
hostname: "{{ grains.id }}"

{{ salt['mdl_saltdata.resolve_leaf_values'](laim.get('config', {})) | yaml(False) }}
